
    - id: 'deploy'
      uses: './'
      with:
          name: 'teste_http'
          runtime: 'python311'
          region: 'us-east1'
          entry_point: 'hello_world'
          source_dir: './teste_http/'
          memory: '128'
          timeout: '30s'
          min_instances: 0
          max_instances: 1000