
      - id: 'deploy'
        uses: './'
        with:
            name: 'http'
            runtime: 'python311'
            region: 'us-east1'
            entry_point: 'hello'
            source_dir: './http/'
            memory: '128'
            timeout: '30s'
            min_instances: 0
            max_instances: 1000