
      - id: 'deploy'
        uses: './'
        with:
            name: 'gcs'
            runtime: 'python311'
            region: 'us-east1'
            entry_point: 'hello'
            source_dir: './gcs/'
            memory: '128'
            timeout: '30s'
            min_instances: 0
            max_instances: 1000
            event_trigger_type: google.storage.object.finalize
            event_trigger_resource: 'projects/_/buckets/est-aut'

        