
    - id: 'deploy'
      uses: './'
      with:
          name: 'sales-integrator'
          runtime: 'python311'
          entry_point: 'read_gcs'
          source_dir: './sales-integrator/'
          memory: '128'
          timeout: '60s'
          min_instances: 0
          max_instances: 1000
          event_trigger_type: google.storage.object.finalize
          event_trigger_resource: 'projects/_/buckets/sales-integrator-deploy-function'

        