on:
  pull_request:
    branches:
      - 'main'
      - 'develop'
    types:
      - closed

  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:

  check_files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check modified files
        id: files
        run: echo "::set-output name=modified_files::$(git diff --name-only HEAD..$GITHUB_SHA)"

  https_trigger:
    if: ${{ github.event.pull_request.merged == true && steps.check_files.outputs.modified_files == 'sales_integrator/*' }}
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v3'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/auth@v0.6.0
        with:
          credentials_json: ${{ github.ref == 'refs/heads/main' && secrets.GOOGLE_APPLICATION_CREDENTIALS || secrets.GOOGLE_APPLICATION_CREDENTIALS_DEV }}
        env:
          MY_OUTPUT_VARIABLE: ${{ steps.step_id.outputs.output_name }}

      - name: Save credentials JSON to file
        run: echo "$GOOGLE_APPLICATION_CREDENTIALS" > "$GITHUB_WORKSPACE/gha-creds.json"
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.setup.outputs.credentials_json }}
        
      - name: Set credentials file as output
        run: echo "{name}=$GITHUB_WORKSPACE/gha-creds.json" >> $GITHUB_OUTPUT
        
      - id: 'deploy'
        uses: './'
        with:
          name: 'sales-integrator'
          runtime: 'python311'
          region: 'us-central1'
          entry_point: 'read_gcs'
          source_dir: './sales_integrator/'
          memory: '128'
          timeout: '60s'
          min_instances: 0
          max_instances: 1000
          event_trigger_type: google.storage.object.finalize
          event_trigger_resource: 'projects/_/buckets/sales-integrator-deploy-function'

        
